name = "skarma-cloudflare-probe"
main = "build/index.js"
compatibility_date = "2026-10-09"
workers_dev = false
[build]
command = "worker-build --release"
[durable_objects]
bindings = [{ name = "PROBE", class_name = "Probe" }]
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Probe"]
